import soot.*;
import soot.jimple.*;

import java.util.*;
import java.util.concurrent.atomic.AtomicInteger;

/**
 * StubInliner – explicit, Soot-API-free inliner for the static stubs that
 * AnalysisTransformer produces via object-sensitive PTA.
 *
 * <p>Usage (inside AnalysisTransformer.internalTransform, after the worklist
 * has finished):
 *
 * <pre>
 *     StubInliner inliner = new StubInliner(new HashSet<>(staticStubCache.values()));
 *     inliner.run();
 *     System.out.println("[Mono/PTA] call sites inlined: " + inliner.getInlinedCount());
 * </pre>
 *
 * <p>Decision order for every StaticInvokeExpr that targets one of our stubs:
 * <ol>
 *   <li>Try full inlining (criteria below). If it succeeds → done.
 *   <li>The call is already a static invoke (dispatch already improved by the
 *       transformer) → leave it; no further action needed.
 *   <li>If the call is still virtual (should not happen after transformation,
 *       but defensively handled) → leave it virtual; we cannot do anything.
 * </ol>
 *
 * <p>Inlining criteria (all must hold):
 * <ul>
 *   <li>Stub body has ≤ {@link #MAX_STUB_UNITS} Jimple statements.
 *   <li>Stub body is loop-free (no back-edges in the unit chain).
 *   <li>Every checked exception declared by the stub is also declared by the
 *       caller (or is a subclass of one that is).
 *   <li>If the stub returns a value, the call site is an {@link AssignStmt}
 *       whose LHS is a {@link Local} that can receive the return value.
 * </ul>
 */
public class StubInliner {

    // -----------------------------------------------------------------------
    // Configuration
    // -----------------------------------------------------------------------

    /**
     * Maximum number of Jimple units in a stub body before we give up
     * inlining it.  Raise if you want more aggressive inlining; lower to
     * keep caller bodies smaller.
     */
    public static final int MAX_STUB_UNITS = 30;

    // -----------------------------------------------------------------------
    // State
    // -----------------------------------------------------------------------

    /** The set of stub SootMethods generated by AnalysisTransformer. */
    private final Set<SootMethod> stubs;

    /** Monotonically increasing counter – guarantees unique local names. */
    private final AtomicInteger seq = new AtomicInteger(0);

    /** Number of call sites successfully inlined (read after {@link #run()}). */
    private int inlinedCount = 0;

    // -----------------------------------------------------------------------
    // Constructor
    // -----------------------------------------------------------------------

    /**
     * @param stubs  All static stub methods produced by AnalysisTransformer
     *               (i.e. {@code new HashSet<>(staticStubCache.values())}).
     */
    public StubInliner(Set<SootMethod> stubs) {
        this.stubs = Collections.unmodifiableSet(new HashSet<>(stubs));
    }

    // -----------------------------------------------------------------------
    // Public API
    // -----------------------------------------------------------------------

    /**
     * Runs the inliner over every reachable application method.  Safe to call
     * multiple times (idempotent on already-inlined sites because those
     * StaticInvokeExprs targeting stubs have been removed).
     */
    public void run() {
        for (SootClass cls : Scene.v().getApplicationClasses()) {
            for (SootMethod method : new ArrayList<>(cls.getMethods())) {
                if (!method.isConcrete() || method.isNative() || !method.hasActiveBody())
                    continue;
                // Process one caller body; snapshot the unit list first because
                // we will be mutating it.
                processBody(method.getActiveBody());
            }
        }
    }

    /** Returns the number of call sites successfully inlined after {@link #run()}. */
    public int getInlinedCount() {
        return inlinedCount;
    }

    // -----------------------------------------------------------------------
    // Per-body processing
    // -----------------------------------------------------------------------

    /**
     * Iterates all statements in {@code callerBody}.  For each
     * {@link StaticInvokeExpr} that targets one of our stubs, calls
     * {@link #tryInline} and records the outcome.
     */
    private void processBody(Body callerBody) {
        for (Unit unit : new ArrayList<>(callerBody.getUnits())) {
            if (!(unit instanceof Stmt))
                continue;

            Stmt stmt = (Stmt) unit;
            if (!stmt.containsInvokeExpr())
                continue;

            InvokeExpr ie = stmt.getInvokeExpr();

            if (ie instanceof StaticInvokeExpr) {
                // The transformer already turned this into a static call.
                SootMethod callee = ie.getMethod();
                if (!stubs.contains(callee))
                    continue; // Not one of our stubs – skip.

                InlineOutcome outcome = tryInline(callerBody, stmt, (StaticInvokeExpr) ie, callee);
                switch (outcome) {
                    case INLINED:
                        inlinedCount++;
                        break;
                    case STATIC_KEPT:
                        // Already a static call – dispatch is already optimal.
                        break;
                    case VIRTUAL_KEPT:
                        // Cannot inline and call is virtual – nothing we can do.
                        System.out.println("[Inline] Virtual call kept (no PTA target): "
                                + stmt + " in " + callerBody.getMethod().getSignature());
                        break;
                }

            } else if (ie instanceof VirtualInvokeExpr || ie instanceof InterfaceInvokeExpr) {
                // A virtual/interface call that the transformer could not devirtualise.
                // We cannot inline it – log and move on.
                SootMethod callee = ie.getMethod();
                if (stubs.contains(callee)) {
                    // This would be unusual (stub should be static) but handle it.
                    System.out.println("[Inline] Unexpected virtual call to stub: "
                            + callee.getSignature() + " in " + callerBody.getMethod().getSignature());
                }
                // Leave the call as-is.
            }
            // SpecialInvokeExpr (<init>, super calls) – never our stubs; skip.
        }
    }

    // -----------------------------------------------------------------------
    // Core inlining logic
    // -----------------------------------------------------------------------

    private enum InlineOutcome { INLINED, STATIC_KEPT, VIRTUAL_KEPT }

    /**
     * Attempts to inline {@code callee} (one of our static stubs) at
     * {@code callStmt} inside {@code callerBody}.
     *
     * <p>Inlining steps:
     * <ol>
     *   <li>Gate checks (size, loops, exceptions, LHS compatibility).
     *   <li>Clone all locals from the stub, giving each a unique prefix.
     *   <li>Clone every non-identity unit from the stub body, and build a
     *       mapping from original units to clones.
     *   <li>Substitute actual arguments for every use of parameter locals
     *       (collected from the stub's own IdentityStmts) in the cloned units.
     *   <li>Substitute cloned locals for every use of stub-local in cloned units.
     *   <li>Remap all branch targets in cloned units to their clones.
     *   <li>Create one {@code exitNop} that all return paths jump to.
     *   <li>Replace every ReturnStmt/ReturnVoidStmt in the clones with
     *       {@code lhs = retVal; goto exitNop} (or just {@code goto exitNop}
     *       for void returns).
     *   <li>Insert the full cloned sequence (plus exitNop) immediately before
     *       {@code callStmt}, then remove {@code callStmt}.
     *   <li>Clone the stub's exception traps with remapped unit references.
     *   <li>Re-validate the caller body (non-fatal warning on failure).
     * </ol>
     */
    private InlineOutcome tryInline(
            Body callerBody,
            Stmt callStmt,
            StaticInvokeExpr callExpr,
            SootMethod callee) {

        if (!callee.hasActiveBody())
            return InlineOutcome.STATIC_KEPT;

        Body calleeBody = callee.getActiveBody();
        List<Unit> calleeUnits = new ArrayList<>(calleeBody.getUnits());

        // ── Gate 1: size ──────────────────────────────────────────────────
        if (calleeUnits.size() > MAX_STUB_UNITS)
            return InlineOutcome.STATIC_KEPT;

        // ── Gate 2: loop-free ─────────────────────────────────────────────
        if (hasBackEdge(calleeUnits))
            return InlineOutcome.STATIC_KEPT;

        // ── Gate 3: checked-exception compatibility ───────────────────────
        if (!checkedExceptionsCompatible(callee, callerBody.getMethod()))
            return InlineOutcome.STATIC_KEPT;

        // ── Gate 4: return-type / LHS compatibility ───────────────────────
        boolean voidReturn = callee.getReturnType() instanceof VoidType;
        Local callLhs = null;
        if (!voidReturn) {
            if (!(callStmt instanceof AssignStmt))
                return InlineOutcome.STATIC_KEPT;
            Value lhsVal = ((AssignStmt) callStmt).getLeftOp();
            if (!(lhsVal instanceof Local))
                return InlineOutcome.STATIC_KEPT;
            callLhs = (Local) lhsVal;
        }

        // ── Step 1: collect parameter→actual mapping from stub IdentityStmts ──
        //
        // The stub body begins with statements like:
        //   r0_explicit := @parameter0: SomeClass   (the receiver)
        //   p1          := @parameter1: int         (first original arg)
        //   ...
        // We build a map  { local → actual argument value }  so we can
        // substitute throughout the cloned body without leaving any
        // IdentityStmt in the caller (which would break Soot validation).
        //
        Map<Local, Value> paramSubst = new HashMap<>();
        List<Value> actuals = callExpr.getArgs(); // arg[0]=receiver, arg[1..N]=original args
        for (Unit u : calleeUnits) {
            if (!(u instanceof IdentityStmt))
                break; // IdentityStmts are always first; stop on the first non-identity
            IdentityStmt id = (IdentityStmt) u;
            if (!(id.getRightOp() instanceof ParameterRef))
                continue;
            int idx = ((ParameterRef) id.getRightOp()).getIndex();
            Local paramLocal = (Local) id.getLeftOp();
            if (idx < actuals.size())
                paramSubst.put(paramLocal, actuals.get(idx));
        }

        // ── Step 2: clone locals ─────────────────────────────────────────
        String prefix = "$il" + seq.incrementAndGet() + "_";
        Map<Local, Local> localClones = new HashMap<>();
        for (Local orig : calleeBody.getLocals()) {
            // Skip parameter locals that are fully substituted by actuals;
            // they will never appear as a def after we strip identity stmts.
            // We still clone them in case they are also used as temporaries
            // elsewhere in the body (rare but possible after optimisations).
            Local clone = Jimple.v().newLocal(prefix + orig.getName(), orig.getType());
            callerBody.getLocals().add(clone);
            localClones.put(orig, clone);
        }

        // ── Step 3: clone non-identity units ─────────────────────────────
        //
        // We skip all leading IdentityStmts.  We do NOT skip IdentityStmts
        // that appear mid-body (e.g. exception catch blocks use them for
        // @caughtexception) – those must be kept.
        //
        List<Unit> toClone = new ArrayList<>();
        boolean pastIdentityBlock = false;
        for (Unit u : calleeUnits) {
            if (!pastIdentityBlock) {
                if (u instanceof IdentityStmt) {
                    Value rhs = ((IdentityStmt) u).getRightOp();
                    // Skip the leading parameter/this identity stmts only.
                    if (rhs instanceof ParameterRef || rhs instanceof ThisRef)
                        continue;
                }
                pastIdentityBlock = true;
            }
            toClone.add(u);
        }

        Map<Unit, Unit> unitClones = new IdentityHashMap<>();
        List<Unit> clonedList = new ArrayList<>();
        for (Unit orig : toClone) {
            Unit cloned = (Unit) orig.clone();
            unitClones.put(orig, cloned);
            clonedList.add(cloned);
        }

        // ── Step 4 & 5: substitute params and remap locals in every cloned unit ──
        for (Unit cloned : clonedList) {
            for (ValueBox box : cloned.getUseAndDefBoxes()) {
                Value v = box.getValue();
                if (v instanceof Local) {
                    Local local = (Local) v;
                    // Parameter substitution takes priority.
                    if (paramSubst.containsKey(local)) {
                        Value actual = paramSubst.get(local);
                        // If types differ we need a cast local in the caller body.
                        // We insert it just before callStmt (which still exists).
                        box.setValue(castIfNeeded(actual, local.getType(), callStmt, callerBody));
                    } else {
                        Local cloneLocal = localClones.get(local);
                        if (cloneLocal != null)
                            box.setValue(cloneLocal);
                    }
                }
            }
        }

        // ── Step 6: remap branch targets ─────────────────────────────────
        for (Unit cloned : clonedList) {
            for (UnitBox ub : cloned.getUnitBoxes()) {
                Unit remapped = unitClones.get(ub.getUnit());
                if (remapped != null)
                    ub.setUnit(remapped);
                // If remapped==null the target was an identity stmt we stripped;
                // that can only happen if a goto jumped INTO the identity block,
                // which is impossible in well-formed Jimple – safe to ignore.
            }
        }

        // ── Step 7: create the single exit nop ───────────────────────────
        NopStmt exitNop = Jimple.v().newNopStmt();

        // ── Step 8: replace return stmts with [ lhs=val; ] goto exitNop ──
        List<Unit> finalUnits = new ArrayList<>();
        for (Unit cloned : clonedList) {
            if (cloned instanceof ReturnVoidStmt) {
                finalUnits.add(Jimple.v().newGotoStmt(exitNop));

            } else if (cloned instanceof ReturnStmt) {
                Value retVal = ((ReturnStmt) cloned).getOp();
                // The return value may itself be a local that needs remapping.
                if (retVal instanceof Local) {
                    Local rl = (Local) retVal;
                    if (paramSubst.containsKey(rl))
                        retVal = paramSubst.get(rl);
                    else if (localClones.containsKey(rl))
                        retVal = localClones.get(rl);
                }
                if (callLhs != null) {
                    Value assignVal = castIfNeeded(retVal, callLhs.getType(), callStmt, callerBody);
                    finalUnits.add(Jimple.v().newAssignStmt(callLhs, assignVal));
                }
                finalUnits.add(Jimple.v().newGotoStmt(exitNop));

            } else {
                finalUnits.add(cloned);
            }
        }
        finalUnits.add(exitNop);

        // Update any intra-body gotos that pointed to a ReturnStmt (now gone)
        // to point to exitNop instead.  We do this by checking every GotoStmt
        // and IfStmt in finalUnits whose target is still the *original* return
        // unit (not yet remapped to a clone of a return).  In practice, our
        // remapping in step 6 already pointed them to the cloned ReturnStmt;
        // but we just replaced those clones above, so the UnitBoxes inside
        // surviving GotoStmts still hold references to the now-discarded clones.
        // We need a second pass: any UnitBox pointing to a discarded clone (a
        // ReturnStmt or ReturnVoidStmt) should be redirected to exitNop.
        Set<Unit> discarded = new HashSet<>();
        for (Unit c : clonedList)
            if (c instanceof ReturnStmt || c instanceof ReturnVoidStmt)
                discarded.add(c);

        for (Unit u : finalUnits) {
            for (UnitBox ub : u.getUnitBoxes()) {
                if (discarded.contains(ub.getUnit()))
                    ub.setUnit(exitNop);
            }
        }

        // ── Step 9: insert cloned body before callStmt, then remove callStmt ──
        for (Unit u : finalUnits)
            callerBody.getUnits().insertBefore(u, callStmt);

        // ── Step 10: clone traps with remapped units ──────────────────────
        for (Trap trap : calleeBody.getTraps()) {
            Unit begin   = unitClones.get(trap.getBeginUnit());
            Unit end     = unitClones.get(trap.getEndUnit());
            Unit handler = unitClones.get(trap.getHandlerUnit());
            if (begin != null && end != null && handler != null) {
                callerBody.getTraps().add(
                        Jimple.v().newTrap(trap.getException(), begin, end, handler));
            }
        }

        // Remove the original call statement.
        callerBody.getUnits().remove(callStmt);

        // ── Step 11: re-validate ──────────────────────────────────────────
        try {
            callerBody.validate();
        } catch (RuntimeException e) {
            System.err.println("[Inline] Post-inline validation warning in "
                    + callerBody.getMethod().getSignature()
                    + " (callee: " + callee.getSignature() + "): " + e.getMessage());
        }

        return InlineOutcome.INLINED;
    }

    // -----------------------------------------------------------------------
    // Helper: cast-if-needed
    // -----------------------------------------------------------------------

    /**
     * Returns {@code value} unchanged if its declared type already matches
     * {@code targetType}, otherwise inserts a cast assignment immediately
     * before {@code anchor} in {@code body} and returns the fresh cast local.
     *
     * <p>The anchor statement must still be present in the body at the time
     * this is called (i.e. before the call-site removal in step 9).
     */
    private Value castIfNeeded(Value value, Type targetType, Stmt anchor, Body body) {
        if (value.getType().equals(targetType))
            return value;

        String name = "$ict" + seq.incrementAndGet();
        Local castLocal = Jimple.v().newLocal(name, targetType);
        body.getLocals().add(castLocal);
        body.getUnits().insertBefore(
                Jimple.v().newAssignStmt(castLocal, Jimple.v().newCastExpr(value, targetType)),
                anchor);
        return castLocal;
    }

    // -----------------------------------------------------------------------
    // Helper: loop detection
    // -----------------------------------------------------------------------

    /**
     * Returns {@code true} if the unit list contains a back-edge, i.e. any
     * branch that jumps to a unit with a smaller (or equal) index.  This is a
     * conservative but sufficient check for our stubs, which are clones of
     * real method bodies that Soot has already validated.
     */
    private boolean hasBackEdge(List<Unit> units) {
        // Build an index map first for O(1) lookup.
        Map<Unit, Integer> idx = new IdentityHashMap<>();
        for (int i = 0; i < units.size(); i++)
            idx.put(units.get(i), i);

        for (Unit u : units) {
            int srcIdx = idx.get(u);
            for (UnitBox ub : u.getUnitBoxes()) {
                Integer dstIdx = idx.get(ub.getUnit());
                if (dstIdx != null && dstIdx <= srcIdx)
                    return true;
            }
        }
        return false;
    }

    // -----------------------------------------------------------------------
    // Helper: checked-exception compatibility
    // -----------------------------------------------------------------------

    /**
     * Returns {@code true} iff every checked exception declared by
     * {@code callee} is also declared by {@code caller} (or is a subclass of
     * a declared exception of {@code caller}).
     *
     * <p>Unchecked exceptions ({@code RuntimeException} and {@code Error}
     * subtypes) are always compatible and do not block inlining.
     */
    private boolean checkedExceptionsCompatible(SootMethod callee, SootMethod caller) {
        List<SootClass> callerThrows = caller.getExceptions();
        outer:
        for (SootClass calleeEx : callee.getExceptions()) {
            if (isUnchecked(calleeEx))
                continue; // Unchecked – always OK.
            for (SootClass callerEx : callerThrows) {
                if (isSubclassOrEqual(calleeEx, callerEx))
                    continue outer; // Covered.
            }
            return false; // This checked exception is not covered by caller.
        }
        return true;
    }

    private boolean isUnchecked(SootClass cls) {
        return isSubclassOrEqual(cls, runtimeException()) || isSubclassOrEqual(cls, error());
    }

    private SootClass runtimeException() {
        return Scene.v().getSootClass("java.lang.RuntimeException");
    }

    private SootClass error() {
        return Scene.v().getSootClass("java.lang.Error");
    }

    /**
     * Returns {@code true} if {@code child} is the same class as {@code parent}
     * or is a subclass of it (walking the superclass chain in the Soot Scene).
     */
    private boolean isSubclassOrEqual(SootClass child, SootClass parent) {
        SootClass cur = child;
        while (cur != null) {
            if (cur.equals(parent))
                return true;
            cur = cur.hasSuperclass() ? cur.getSuperclass() : null;
        }
        return false;
    }
}
